---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pulpocon-app
  labels:
    app: pulpocon-app
spec:
  replicas: 10

  # Here we define the rolling update strategy
  # - maxSurge defines how many pods we can add at a time
  # - maxUnavailable defines how many pods can be unavailable
  #   during the rolling update
  #
  # Setting maxUnavailable to 0 would make sure we have the appropriate
  # capacity during the rolling update.
  # We could also use percentage based values instead of integer.
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0

  # The selector field tells the deployment which pods to update with
  # the new version. This field is optional, but if you have labels
  # uniquely defined for the pod, in this case the "version" label,
  # its necessary to redefine the matchLabels and eliminate the version field
  selector:
    matchLabels:
      app: pulpocon-app
  template:
    metadata:
      labels:
        app: pulpocon-app
        version: v2.0.0
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9101"
    spec:
      containers:
      - name: pulpocon-app
        image: pazgzlez/k8s-deployment-strategies:v2.0.0
        ports:
        - name: http
          containerPort: 8080
        - name: probe
          containerPort: 8086
        env:
        - name: VERSION
          value: v2.0.0
        livenessProbe:
          httpGet:
            path: /live
            port: probe
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /ready
            port: probe

          # Intial delay is set to a high value to have a better
          # visibility of the ramped deployment
          initialDelaySeconds: 15
          periodSeconds: 5
