---
apiVersion: v1
kind: Service
metadata:
  name: pulpocon-app 
  labels:
    app: pulpocon-app 
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: pulpocon-app
    # All stratagies has the selector by app
    # except blue-green that we add the version too
    # could switch blue and green
    # version: v1.0.0

