---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pulpocon-app
  labels:
    app: pulpocon-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pulpocon-app
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: pulpocon-app
  template:
    metadata:
      labels:
        app: pulpocon-app
        version: v1.0.0
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9101"
    spec:
      containers:
      - name: pulpocon-app
        image: pazgzlez/k8s-deployment-strategies:v1.0.0
        ports:
        - name: http
          containerPort: 8080
        - name: probe
          containerPort: 8086
        env:
        - name: VERSION
          value: v1.0.0
        livenessProbe:
          httpGet:
            path: /live
            port: probe
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /ready
            port: probe
          periodSeconds: 5

